name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go get -u github.com/prometheus/client_golang/prometheus
          go get -u github.com/prometheus/client_golang/prometheus/promhttp

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o jstat_exporter jstat_exporter.go
          GOOS=darwin GOARCH=amd64 go build -o jstat_exporter-darwin-amd64 jstat_exporter.go
          GOOS=windows GOARCH=amd64 go build -o jstat_exporter-windows-amd64.exe jstat_exporter.go

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.release.name }}
          release_name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}
          draft: false
          prerelease: false
          commitish: main
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: jstat_exporter
          asset_name: jstat_exporter

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: jstat_exporter-darwin-amd64
          asset_name: jstat_exporter-darwin-amd64

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: jstat_exporter-windows-amd64.exe
          asset_name: jstat_exporter-windows-amd64.exe
