name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go get -u github.com/prometheus/client_golang/prometheus
          go get -u github.com/prometheus/client_golang/prometheus/promhttp

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o jstat_exporter jstat_exporter.go
          GOOS=darwin GOARCH=amd64 go build -o jstat_exporter-darwin-amd64 jstat_exporter.go
          GOOS=windows GOARCH=amd64 go build -o jstat_exporter-windows-amd64.exe jstat_exporter.go

      - name: Create release
        uses: actions/create-release@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ github.event.release.name }}
          release_body: ${{ github.event.release.body }}

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ github.event.release.id }}
          file: jstat_exporter
          file_name: jstat_exporter-linux-amd64

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ github.event.release.id }}
          file: jstat_exporter-darwin-amd64
          file_name: jstat_exporter-darwin-amd64

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ github.event.release.id }}
          file: jstat_exporter-windows-amd64.exe
          file_name: jstat_exporter-windows-amd64.exe
